package com.moonsonglabs.daml.sandbox

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.file.Files

class SandboxGeneratorTest {
    @Test
    fun `generates local canton jar recipe files`() {
        val root = Files.createTempDirectory("managed-canton-sandbox")
        val profile = SandboxDefaults.newProfile(root).apply {
            id = "test-sandbox"
            generatedPath = root.resolve(".canton-sandboxes/test-sandbox").toString()
            participants.add(SandboxDefaults.participant(2, portBase))
            bindings.add(ParticipantSyncBinding(participants[1].id, synchronizers[0].id, true))
            partyAllocations.add(PartyAllocation("Bob", participants[1].id, synchronizers[0].id))
        }
        Files.createDirectories(root.resolve(".canton-sandboxes/test-sandbox/logs"))
        Files.createDirectories(root.resolve(".canton-sandboxes/test-sandbox/data"))

        val generated = SandboxGenerator().generate(profile)
        val conf = Files.readString(generated.localConfig)
        val bootstrap = Files.readString(generated.localBootstrap)
        val run = Files.readString(generated.localRunScript)
        val gitignore = Files.readString(generated.root.resolve(".gitignore"))
        val profileJson = Files.readString(generated.profileJson)

        assertTrue(conf.contains("sequencers {"))
        assertTrue(conf.contains("participants {"))
        assertTrue(conf.contains("issuer {"))
        assertTrue(conf.contains("investor {"))
        assertTrue(conf.contains("ledger-api      { address = \"0.0.0.0\", port = 5011 }") || conf.contains("ledger-api { address = \"0.0.0.0\" port = 5011 }"))
        assertTrue(conf.contains("http-ledger-api { address = \"0.0.0.0\", port = 7575 }"))
        assertTrue(conf.contains("http-ledger-api { address = \"0.0.0.0\", port = 7576 }"))

        assertTrue(bootstrap.contains("nodes.local.start()"))
        assertTrue(bootstrap.contains("bootstrap.synchronizer("))
        assertTrue(bootstrap.contains("synchronizerOwners = Seq(globalSequencer, globalMediator)"))
        assertTrue(bootstrap.contains("issuer.synchronizers.connect_local(globalSequencer, alias = \"global\")"))
        assertTrue(bootstrap.contains("issuer.parties.enable(\"Bank\", synchronizer = Some(\"global\"), synchronizeParticipants = Seq(issuer))"))
        assertTrue(bootstrap.contains("investor.parties.enable(\"Bob\", synchronizer = Some(\"global\"), synchronizeParticipants = Seq(investor))"))
        assertTrue(bootstrap.contains("=== sandbox ready ==="))

        assertTrue(run.contains("CANTON_JAR_DEFAULT="))
        assertTrue(run.contains("CONF=\"canton.conf\""))
        assertTrue(run.contains("BOOT=\"bootstrap.canton\""))
        assertTrue(run.contains("LOG_DIR=\"log\""))
        assertTrue(run.contains("cd \"${'$'}HERE\""))
        assertTrue(run.contains("exec java -jar \"${'$'}CANTON_JAR\" daemon -c \"${'$'}CONF\" --bootstrap \"${'$'}BOOT\""))
        assertTrue(generated.localRunScript.toFile().canExecute())
        assertTrue("Empty top-level logs directory should not be generated.", !Files.exists(generated.root.resolve("logs")))
        assertTrue("Memory storage does not need a data directory.", !Files.exists(generated.root.resolve("data")))
        assertTrue("DARs are referenced in place; no dars/ directory is generated.", !Files.exists(generated.root.resolve("dars")))
        assertEquals(generated.root.resolve("local/log"), generated.logsDir)
        assertTrue(gitignore.contains("local/log/"))
        assertFalse("dars/ is no longer generated, so it must not be gitignored.", gitignore.contains("dars/"))
        assertTrue(gitignore.contains("participants.json"))
        assertTrue(profileJson.contains(""""workspacePath": ".""""))
        assertTrue(profileJson.contains(""""generatedPath": ".canton-sandboxes/test-sandbox""""))
        assertFalse("Generated profile must not persist absolute workspace paths.", profileJson.contains(root.toString()))
        assertTrue("Docker Compose files should not be generated by the local-only sandbox feature.", !Files.exists(generated.root.resolve("docker/docker-compose.yaml")))
    }

    @Test
    fun `party allocations are generated against explicit synchronizers`() {
        val profile = SandboxDefaults.newProfile(Files.createTempDirectory("managed-canton-multi-sync")).apply {
            id = "multi-sync"
            synchronizers.add(SandboxDefaults.synchronizer(2, portBase))
            bindings.clear()
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[0].id, true))
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[1].id, true))
            partyAllocations.clear()
            partyAllocations.add(PartyAllocation("Bank", participants[0].id, synchronizers[0].id))
            partyAllocations.add(PartyAllocation("Bank", participants[0].id, synchronizers[1].id))
        }

        val allocationScript = SandboxGenerator().allocationScript(profile)

        assertTrue(allocationScript.contains("issuer.parties.enable(\"Bank\", synchronizer = Some(\"global\"), synchronizeParticipants = Seq(issuer))"))
        assertTrue(allocationScript.contains("issuer.parties.enable(\"Bank\", synchronizer = Some(\"sync2\"), synchronizeParticipants = Seq(issuer))"))
    }

    @Test
    fun `dar uploads are vetted on every connected synchronizer`() {
        val root = Files.createTempDirectory("managed-canton-multi-sync-dars")
        val darDir = Files.createDirectories(root.resolve(".daml/dist"))
        Files.writeString(darDir.resolve("example.dar"), "dar")
        val profile = SandboxDefaults.newProfile(root).apply {
            id = "multi-sync-dars"
            synchronizers.add(SandboxDefaults.synchronizer(2, portBase))
            bindings.clear()
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[0].id, true))
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[1].id, true))
            darAssignments.add(DarAssignment(".daml/dist/example.dar", mutableListOf(participants[0].id)))
        }

        val uploadScript = SandboxGenerator().uploadScript(profile)

        assertTrue(uploadScript.contains("issuer.dars.upload(\".daml/dist/example.dar\", synchronizerId = Some(issuer.synchronizers.id_of(\"global\")))"))
        assertTrue(uploadScript.contains("issuer.dars.upload(\".daml/dist/example.dar\", synchronizerId = Some(issuer.synchronizers.id_of(\"sync2\")))"))
        assertFalse(uploadScript.contains(root.toString()))
    }

    @Test
    fun `dars are referenced in place without copying`() {
        val root = Files.createTempDirectory("managed-canton-dars-inplace")
        val dar1 = Files.writeString(root.resolve("one.dar"), "one")
        val profile = SandboxDefaults.newProfile(root).apply {
            id = "dar-inplace"
            generatedPath = root.resolve(".canton-sandboxes/dar-inplace").toString()
            darAssignments.add(DarAssignment(dar1.toString(), mutableListOf(participants[0].id)))
        }

        val generated = SandboxGenerator().generate(profile)

        assertFalse("DARs must not be copied into a dars/ directory.", Files.exists(generated.root.resolve("dars")))
        val bootstrapDarPath = SandboxPaths.relativePath(generated.localBootstrap.parent, dar1)
        val uploadDarPath = SandboxPaths.relativePath(generated.root, dar1)
        assertTrue(Files.readString(generated.localBootstrap).contains("issuer.dars.upload(\"$bootstrapDarPath\""))
        assertTrue(Files.readString(generated.uploadScript).contains("issuer.dars.upload(\"$uploadDarPath\""))
        assertFalse(Files.readString(generated.profileJson).contains(root.toString()))
    }

    @Test
    fun `updating generated files refreshes profile and dar scripts without cleanup`() {
        val root = Files.createTempDirectory("managed-canton-dars-update")
        val dar1 = Files.writeString(root.resolve("one.dar"), "one")
        val profile = SandboxDefaults.newProfile(root).apply {
            id = "dar-update"
            generatedPath = root.resolve(".canton-sandboxes/dar-update").toString()
            darAssignments.add(DarAssignment(dar1.toString(), mutableListOf(participants[0].id)))
        }
        val generator = SandboxGenerator()
        val generated = generator.generate(profile)
        Files.createDirectories(generated.root.resolve("data"))
        Files.writeString(generated.root.resolve("data/runtime.txt"), "keep")

        val dar2 = Files.writeString(root.resolve("two.dar"), "two")
        profile.darAssignments.clear()
        profile.darAssignments.add(DarAssignment(dar2.toString(), mutableListOf(profile.participants[0].id)))

        generator.updateGeneratedFiles(profile)

        assertTrue(Files.exists(generated.root.resolve("data/runtime.txt")))
        assertTrue(Files.readString(generated.profileJson).contains("two.dar"))
        assertTrue(Files.readString(generated.uploadScript).contains("two.dar"))
        assertFalse(Files.readString(generated.uploadScript).contains("one.dar"))
    }

    @Test
    fun `relative profile paths are resolved against the project root`() {
        val root = Files.createTempDirectory("managed-canton-relative-profile")
        val darDir = Files.createDirectories(root.resolve("dist"))
        Files.writeString(darDir.resolve("relative.dar"), "dar")
        val profile = SandboxDefaults.newProfile(null).apply {
            id = "relative-profile"
            workspacePath = "."
            generatedPath = ".canton-sandboxes/relative-profile"
            darAssignments.add(DarAssignment("dist/relative.dar", mutableListOf(participants[0].id)))
        }

        val generated = SandboxGenerator(root).generate(profile)

        assertEquals(root.resolve(".canton-sandboxes/relative-profile"), generated.root)
        assertFalse("DARs must not be copied into a dars/ directory.", Files.exists(generated.root.resolve("dars")))
        val sourceDar = root.resolve("dist/relative.dar")
        val bootstrapDarPath = SandboxPaths.relativePath(generated.localBootstrap.parent, sourceDar)
        val uploadDarPath = SandboxPaths.relativePath(generated.root, sourceDar)
        assertTrue(Files.readString(generated.localBootstrap).contains("issuer.dars.upload(\"$bootstrapDarPath\""))
        assertTrue(Files.readString(generated.uploadScript).contains("issuer.dars.upload(\"$uploadDarPath\""))
        assertFalse(Files.readString(generated.profileJson).contains(root.toString()))
    }

    @Test
    fun `default profile mirrors two participant recipe ports when second participant is added`() {
        val profile = SandboxDefaults.newProfile(null).apply {
            participants.add(SandboxDefaults.participant(2, portBase))
        }
        assertEquals("issuer", profile.participants[0].name)
        assertEquals(5011, profile.participants[0].ledgerPort)
        assertEquals(5012, profile.participants[0].adminPort)
        assertEquals(7575, profile.participants[0].jsonPort)
        assertEquals("investor", profile.participants[1].name)
        assertEquals(5021, profile.participants[1].ledgerPort)
        assertEquals(5022, profile.participants[1].adminPort)
        assertEquals(7576, profile.participants[1].jsonPort)
        assertEquals("global", profile.synchronizers[0].name)
        assertEquals(5001, profile.synchronizers[0].sequencer.publicPort)
        assertEquals(5002, profile.synchronizers[0].sequencer.adminPort)
        assertEquals(5202, profile.synchronizers[0].mediator.adminPort)
    }
}
